// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RebelTours.Persistence.RebelToursDbContext;

namespace RebelTours.Persistence.Migrations
{
    [DbContext(typeof(FluentDbContext))]
    [Migration("20220331120831_CityMigrations")]
    partial class CityMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RebelTours.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Adana"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Antalya"
                        },
                        new
                        {
                            Id = 4,
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ordu"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Zonguldak"
                        });
                });

            modelBuilder.Entity("RebelTours.Domain.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Adana Terminali"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Name = "Aşti"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 4,
                            Name = "Harem"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Name = "Dudullu"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 4,
                            Name = "Esenler Otagarı"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Name = "Kaş Otogarı"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 5,
                            Name = "Fındık Terminali"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 6,
                            Name = "100.Yıl Terminalli"
                        });
                });

            modelBuilder.Entity("RebelTours.Domain.Station", b =>
                {
                    b.HasOne("RebelTours.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
